/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Oct 08 22:31:57 GMT 2018
 */

package org.jabref.logic.bibtex;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class BibEntryWriter_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.jabref.logic.bibtex.BibEntryWriter"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\CLAUDI~1\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "E:\\ClaudineiBJr\\Outros\\K2\\source\\jabref-4.2"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Claudinei B Jr"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "Claudinei B Jr"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(BibEntryWriter_ESTest_scaffolding.class.getClassLoader() ,
      "org.jabref.model.entry.event.EntryEvent",
      "org.jabref.model.entry.BibtexSingleField$FieldType",
      "org.jabref.model.database.BibDatabase",
      "org.jabref.logic.bibtex.LatexFieldFormatterPreferences",
      "org.jabref.model.metadata.ContentSelector",
      "org.jabref.model.groups.KeywordGroup",
      "org.jabref.model.entry.CustomEntryType",
      "org.jabref.model.entry.event.EntryChangedEvent",
      "org.jabref.model.groups.GroupHierarchyType",
      "org.jabref.logic.bibtex.FieldContentParserPreferences",
      "org.jabref.model.TreeNode",
      "org.jabref.model.database.BibDatabaseMode",
      "org.jabref.model.entry.Date",
      "org.jabref.model.strings.StringUtil",
      "org.jabref.logic.bibtex.LatexFieldFormatter",
      "org.jabref.model.database.KeyCollisionException",
      "org.jabref.model.metadata.ContentSelectors",
      "org.jabref.model.entry.specialfields.SpecialField",
      "org.jabref.model.entry.LinkedFile",
      "org.jabref.model.entry.specialfields.SpecialFieldValue",
      "org.jabref.model.groups.AbstractGroup",
      "org.jabref.logic.bibtex.InvalidFieldValueException",
      "org.jabref.model.metadata.MetaData",
      "org.jabref.model.entry.BiblatexEntryTypes$2",
      "org.jabref.model.database.shared.DatabaseSynchronizer",
      "org.jabref.model.entry.BiblatexEntryTypes$1",
      "org.jabref.model.entry.BiblatexEntryTypes$4",
      "org.jabref.model.entry.BiblatexEntryTypes$3",
      "org.jabref.model.entry.BiblatexEntryTypes$6",
      "org.jabref.model.entry.BiblatexEntryTypes$5",
      "org.jabref.model.entry.BiblatexEntryTypes$8",
      "org.jabref.model.entry.BiblatexEntryType",
      "org.jabref.model.entry.BiblatexEntryTypes$7",
      "org.jabref.model.bibtexkeypattern.AbstractBibtexKeyPattern",
      "org.jabref.model.metadata.FileDirectoryPreferences",
      "org.jabref.logic.bibtex.BibEntryWriter",
      "org.jabref.model.entry.SharedBibEntryData",
      "org.jabref.model.entry.IEEETranEntryTypes",
      "org.jabref.model.search.SearchMatcher",
      "org.jabref.model.groups.GroupEntryChanger",
      "org.jabref.model.entry.BiblatexEntryTypes$9",
      "org.jabref.model.database.event.EntryRemovedEvent",
      "org.jabref.model.Defaults",
      "org.jabref.model.entry.BiblatexEntryTypes$21",
      "org.jabref.model.entry.BiblatexEntryTypes$22",
      "org.jabref.model.entry.BiblatexEntryTypes$23",
      "org.jabref.model.database.shared.DatabaseConnectionProperties",
      "org.jabref.model.entry.BiblatexEntryTypes$24",
      "org.jabref.model.entry.BiblatexEntryTypes$25",
      "org.jabref.model.entry.BiblatexEntryTypes$26",
      "org.jabref.model.entry.BiblatexEntryTypes$27",
      "org.jabref.model.entry.BiblatexEntryTypes$28",
      "org.jabref.model.entry.BiblatexEntryTypes$20",
      "org.jabref.model.entry.event.FieldChangedEvent",
      "org.jabref.model.entry.BibtexString",
      "org.jabref.model.database.event.EntryAddedEvent",
      "org.jabref.model.entry.BibtexEntryTypes",
      "org.jabref.model.entry.InternalBibtexFields",
      "org.jabref.model.entry.BiblatexEntryTypes$29",
      "org.jabref.model.entry.Keyword",
      "org.jabref.model.database.shared.DBMSType",
      "org.jabref.model.entry.BiblatexEntryTypes$32",
      "org.jabref.model.EntryTypes",
      "org.jabref.model.entry.BiblatexEntryTypes$33",
      "org.jabref.model.entry.BiblatexEntryTypes$34",
      "org.jabref.model.entry.BiblatexEntryTypes",
      "org.jabref.model.entry.BibEntry",
      "org.jabref.model.ChainNode",
      "org.jabref.model.cleanup.FieldFormatterCleanups",
      "org.jabref.model.entry.BibtexEntryType",
      "org.jabref.model.entry.BibtexSingleField",
      "org.jabref.model.entry.BiblatexEntryTypes$30",
      "org.jabref.model.entry.BiblatexEntryTypes$31",
      "org.jabref.model.entry.BibEntry$GetFieldInterface",
      "org.jabref.logic.util.OS",
      "org.jabref.model.entry.IEEETranEntryTypes$5",
      "org.jabref.model.entry.IEEETranEntryTypes$1",
      "org.jabref.model.database.event.ChangePropagation",
      "org.jabref.model.entry.IEEETranEntryTypes$2",
      "org.jabref.model.entry.IEEETranEntryTypes$3",
      "org.jabref.model.entry.IEEETranEntryTypes$4",
      "org.jabref.model.entry.FieldProperty",
      "org.jabref.logic.bibtex.FieldContentParser",
      "org.jabref.model.entry.FieldName",
      "org.jabref.model.entry.KeywordList",
      "org.jabref.model.entry.BibtexEntryTypes$10",
      "org.jabref.model.entry.BibtexEntryTypes$2",
      "org.jabref.model.entry.BibtexEntryTypes$13",
      "org.jabref.model.entry.BibtexEntryTypes$3",
      "org.jabref.model.entry.BibtexEntryTypes$14",
      "org.jabref.model.entry.BibtexEntryTypes$11",
      "org.jabref.model.entry.BibtexEntryTypes$1",
      "org.jabref.model.entry.BibtexEntryTypes$12",
      "org.jabref.model.groups.ExplicitGroup",
      "org.jabref.model.database.shared.DatabaseNotSupportedException",
      "org.jabref.model.database.DuplicationChecker",
      "org.jabref.model.groups.GroupTreeNode",
      "org.jabref.model.groups.WordKeywordGroup",
      "org.jabref.model.bibtexkeypattern.DatabaseBibtexKeyPattern",
      "org.jabref.model.database.shared.DatabaseLocation",
      "org.jabref.model.database.shared.DatabaseConnection",
      "org.jabref.model.database.BibDatabaseContext",
      "org.jabref.model.entry.BiblatexEntryTypes$10",
      "org.jabref.model.entry.BiblatexEntryTypes$11",
      "org.jabref.model.entry.BiblatexEntryTypes$12",
      "org.jabref.model.entry.BiblatexEntryTypes$13",
      "org.jabref.model.entry.event.EntryEventSource",
      "org.jabref.model.entry.BiblatexEntryTypes$14",
      "org.jabref.model.entry.BiblatexEntryTypes$15",
      "org.jabref.model.metadata.SaveOrderConfig",
      "org.jabref.model.entry.BiblatexEntryTypes$16",
      "org.jabref.model.bibtexkeypattern.GlobalBibtexKeyPattern",
      "org.jabref.model.entry.BiblatexEntryTypes$17",
      "org.jabref.model.entry.BibtexString$Type",
      "org.jabref.model.entry.IdGenerator",
      "org.jabref.model.EntryTypes$InternalEntryTypes",
      "org.jabref.model.metadata.SaveOrderConfig$SortCriterion",
      "org.jabref.model.entry.BibtexEntryTypes$6",
      "org.jabref.model.database.event.BibDatabaseContextChangedEvent",
      "org.jabref.model.entry.BibtexEntryTypes$7",
      "org.jabref.model.entry.BibtexEntryTypes$4",
      "org.jabref.model.entry.BibtexEntryTypes$5",
      "org.jabref.model.strings.UnicodeToReadableCharMap",
      "org.jabref.model.entry.BibtexEntryTypes$8",
      "org.jabref.model.entry.BibtexEntryTypes$9",
      "org.jabref.model.entry.BiblatexEntryTypes$18",
      "org.jabref.model.entry.Month",
      "org.jabref.model.entry.BiblatexEntryTypes$19",
      "org.jabref.model.entry.EntryType"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(BibEntryWriter_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.jabref.logic.bibtex.BibEntryWriter",
      "org.jabref.logic.util.OS",
      "org.jabref.model.entry.BibtexEntryType",
      "org.jabref.model.entry.BibtexEntryTypes$1",
      "org.jabref.model.entry.BibtexEntryTypes$2",
      "org.jabref.model.entry.FieldName",
      "org.jabref.model.entry.BibtexEntryTypes$3",
      "org.jabref.model.entry.BibtexEntryTypes$4",
      "org.jabref.model.entry.BibtexEntryTypes$5",
      "org.jabref.model.entry.BibtexEntryTypes$6",
      "org.jabref.model.entry.BibtexEntryTypes$7",
      "org.jabref.model.entry.BibtexEntryTypes$8",
      "org.jabref.model.entry.BibtexEntryTypes$9",
      "org.jabref.model.entry.BibtexEntryTypes$10",
      "org.jabref.model.entry.BibtexEntryTypes$11",
      "org.jabref.model.entry.BibtexEntryTypes$12",
      "org.jabref.model.entry.BibtexEntryTypes$13",
      "org.jabref.model.entry.BibtexEntryTypes$14",
      "org.jabref.model.entry.BibtexEntryTypes",
      "org.jabref.model.entry.IEEETranEntryTypes$1",
      "org.jabref.model.entry.IEEETranEntryTypes$2",
      "org.jabref.model.entry.IEEETranEntryTypes$3",
      "org.jabref.model.entry.IEEETranEntryTypes$4",
      "org.jabref.model.entry.IEEETranEntryTypes$5",
      "org.jabref.model.entry.IEEETranEntryTypes",
      "org.jabref.model.entry.BiblatexEntryType",
      "org.jabref.model.entry.BiblatexEntryTypes$1",
      "org.jabref.model.entry.BiblatexEntryTypes$2",
      "org.jabref.model.entry.BiblatexEntryTypes$3",
      "org.jabref.model.entry.BiblatexEntryTypes$4",
      "org.jabref.model.entry.BiblatexEntryTypes$5",
      "org.jabref.model.entry.BiblatexEntryTypes$6",
      "org.jabref.model.entry.BiblatexEntryTypes$7",
      "org.jabref.model.entry.BiblatexEntryTypes$8",
      "org.jabref.model.entry.BiblatexEntryTypes$9",
      "org.jabref.model.entry.BiblatexEntryTypes$10",
      "org.jabref.model.entry.BiblatexEntryTypes$11",
      "org.jabref.model.entry.BiblatexEntryTypes$12",
      "org.jabref.model.entry.BiblatexEntryTypes$13",
      "org.jabref.model.entry.BiblatexEntryTypes$14",
      "org.jabref.model.entry.BiblatexEntryTypes$15",
      "org.jabref.model.entry.BiblatexEntryTypes$16",
      "org.jabref.model.entry.BiblatexEntryTypes$17",
      "org.jabref.model.entry.BiblatexEntryTypes$18",
      "org.jabref.model.entry.BiblatexEntryTypes$19",
      "org.jabref.model.entry.BiblatexEntryTypes$20",
      "org.jabref.model.entry.BiblatexEntryTypes$21",
      "org.jabref.model.entry.BiblatexEntryTypes$22",
      "org.jabref.model.entry.BiblatexEntryTypes$23",
      "org.jabref.model.entry.BiblatexEntryTypes$24",
      "org.jabref.model.entry.BiblatexEntryTypes$25",
      "org.jabref.model.entry.BiblatexEntryTypes$26",
      "org.jabref.model.entry.BiblatexEntryTypes$27",
      "org.jabref.model.entry.BiblatexEntryTypes$28",
      "org.jabref.model.entry.BiblatexEntryTypes$29",
      "org.jabref.model.entry.BiblatexEntryTypes$30",
      "org.jabref.model.entry.BiblatexEntryTypes$31",
      "org.jabref.model.entry.BiblatexEntryTypes$32",
      "org.jabref.model.entry.BiblatexEntryTypes$33",
      "org.jabref.model.entry.BiblatexEntryTypes$34",
      "org.jabref.model.entry.BiblatexEntryTypes",
      "org.jabref.model.database.BibDatabaseMode",
      "org.jabref.model.EntryTypes$InternalEntryTypes",
      "org.jabref.model.EntryTypes",
      "org.jabref.model.ChainNode",
      "org.jabref.model.entry.Keyword",
      "org.jabref.model.entry.specialfields.SpecialFieldValue",
      "org.jabref.model.entry.KeywordList",
      "org.jabref.model.entry.specialfields.SpecialField",
      "org.jabref.model.entry.BibtexSingleField",
      "org.jabref.model.entry.BibtexSingleField$FieldType",
      "org.jabref.model.entry.FieldProperty",
      "org.jabref.model.entry.InternalBibtexFields",
      "org.jabref.model.metadata.SaveOrderConfig",
      "org.jabref.model.entry.BibEntry",
      "org.jabref.model.entry.IdGenerator",
      "org.jabref.logic.bibtex.LatexFieldFormatterPreferences",
      "org.jabref.logic.bibtex.FieldContentParserPreferences",
      "org.jabref.logic.bibtex.LatexFieldFormatter",
      "org.jabref.logic.bibtex.FieldContentParser",
      "org.jabref.model.database.BibDatabase",
      "org.jabref.model.database.DuplicationChecker",
      "org.jabref.logic.bibtex.InvalidFieldValueException",
      "org.jabref.model.bibtexkeypattern.AbstractBibtexKeyPattern",
      "org.jabref.model.metadata.MetaData",
      "org.jabref.model.bibtexkeypattern.GlobalBibtexKeyPattern",
      "org.jabref.model.metadata.SaveOrderConfig$SortCriterion",
      "org.jabref.model.metadata.ContentSelector",
      "org.jabref.model.database.BibDatabaseContext",
      "org.jabref.model.Defaults",
      "org.jabref.model.cleanup.FieldFormatterCleanups",
      "org.jabref.model.entry.CustomEntryType",
      "org.jabref.model.strings.UnicodeToReadableCharMap",
      "org.jabref.model.strings.StringUtil",
      "org.jabref.model.bibtexkeypattern.DatabaseBibtexKeyPattern",
      "org.jabref.model.groups.AbstractGroup",
      "org.jabref.model.groups.KeywordGroup",
      "org.jabref.model.groups.WordKeywordGroup",
      "org.jabref.model.groups.ExplicitGroup"
    );
  }
}
