/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 08 22:31:57 GMT 2018
 */

package org.jabref.logic.bibtex;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.io.Writer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileWriter;
import org.jabref.logic.bibtex.BibEntryWriter;
import org.jabref.logic.bibtex.LatexFieldFormatter;
import org.jabref.logic.bibtex.LatexFieldFormatterPreferences;
import org.jabref.model.database.BibDatabaseMode;
import org.jabref.model.entry.BibEntry;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BibEntryWriter_ESTest extends BibEntryWriter_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      LatexFieldFormatterPreferences latexFieldFormatterPreferences0 = new LatexFieldFormatterPreferences();
      LatexFieldFormatter latexFieldFormatter0 = LatexFieldFormatter.buildIgnoreHashes(latexFieldFormatterPreferences0);
      BibEntryWriter bibEntryWriter0 = new BibEntryWriter(latexFieldFormatter0, false);
      MockFileWriter mockFileWriter0 = null;
      //try {
    	  mockFileWriter0 = new MockFileWriter("__string", false);
      //}catch (Exception ex) {
    	  //System.out.println("ex: " + ex.getMessage());
    	  //System.out.println("ex: " + ex.getCause());
    	  //System.out.println("ex: " + ex.getClass());
    	  //System.out.println("ex: " + ex.getLocalizedMessage());
    	  //System.out.println("ex: " + ex.getStackTrace());
      //}
      BibDatabaseMode bibDatabaseMode0 = BibDatabaseMode.BIBLATEX;
      // Undeclared exception!
      try { 
        bibEntryWriter0.writeWithoutPrependedNewlines((BibEntry) null, mockFileWriter0, bibDatabaseMode0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jabref.logic.bibtex.BibEntryWriter", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LatexFieldFormatterPreferences latexFieldFormatterPreferences0 = new LatexFieldFormatterPreferences();
      LatexFieldFormatter latexFieldFormatter0 = new LatexFieldFormatter(latexFieldFormatterPreferences0);
      BibEntryWriter bibEntryWriter0 = new BibEntryWriter(latexFieldFormatter0, false);
      BibDatabaseMode bibDatabaseMode0 = BibDatabaseMode.BIBTEX;
      Boolean boolean0 = Boolean.valueOf("/M6b0N=bFEbD3\"q");
      // Undeclared exception!
      try { 
        bibEntryWriter0.write((BibEntry) null, (Writer) null, bibDatabaseMode0, boolean0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jabref.logic.bibtex.BibEntryWriter", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      LatexFieldFormatterPreferences latexFieldFormatterPreferences0 = new LatexFieldFormatterPreferences();
      LatexFieldFormatter latexFieldFormatter0 = new LatexFieldFormatter(latexFieldFormatterPreferences0);
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(709);
      BibEntryWriter bibEntryWriter0 = new BibEntryWriter(latexFieldFormatter0, false);
      BibDatabaseMode bibDatabaseMode0 = BibDatabaseMode.BIBTEX;
      Boolean boolean0 = Boolean.TRUE;
      // Undeclared exception!
      try { 
        bibEntryWriter0.write((BibEntry) null, (Writer) charArrayWriter0, bibDatabaseMode0, boolean0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jabref.logic.bibtex.BibEntryWriter", e);
      }
  }

  @Test
  public void test3()  throws Throwable  {
      LatexFieldFormatterPreferences latexFieldFormatterPreferences0 = new LatexFieldFormatterPreferences();
      LatexFieldFormatter latexFieldFormatter0 = new LatexFieldFormatter(latexFieldFormatterPreferences0);
      BibEntryWriter bibEntryWriter0 = new BibEntryWriter(latexFieldFormatter0, false);
      BibDatabaseMode bibDatabaseMode0 = BibDatabaseMode.BIBTEX;
      // Undeclared exception!
      try { 
        bibEntryWriter0.write((BibEntry) null, (Writer) null, bibDatabaseMode0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jabref.logic.bibtex.BibEntryWriter", e);
      }
  }
}
